out_dir: results
metric_best: mae
metric_agg: argmin
wandb:
  use: True
  project: molfreesolv
dataset:
  format: OGB
  name: ogbg-molfreesolv
  task: graph
  task_type: regression
  transductive: False
  node_encoder: True
  node_encoder_name: Atom+RWSE
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
  split_mode: 'random'
  split: [ 0.7,0.2,0.1 ]

posenc_RWSE:
  enable: True
  kernel:
    times_func: range(1,17)
  model: Linear
  dim_pe: 4

train:
  mode: custom
  batch_size: 1024
  eval_period: 1
  ckpt_period: 100
model:
  type: GPSModel
  loss_fun: l1
  graph_pooling: mean
gt:
  layer_type: CustomGatedGCN+Mamba_yuanzi
  layers: 2
  n_heads: 1
  dim_hidden: 32  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.0
  attn_dropout: 0.0
  layer_norm: False
  batch_norm: False
gnn:
  head: default
  layers_pre_mp: 0
  layers_post_mp: 1  # Not used when `gnn.head: san_graph`
  dim_inner: 32  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: False
  act: relu
  dropout: 0.0
  agg: mean
  normalize_adj: False
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 0.0
  base_lr: 0.008
  max_epoch: 500
  scheduler: cosine_with_warmup
  num_warmup_epochs: 5
#optim:
#  clip_grad_norm: True
#  optimizer: adamW
#  weight_decay: 1e-5
#  base_lr: 0.0001
#  max_epoch: 100
#  scheduler: reduce_on_plateau
#  reduce_factor: 0.5
#  schedule_patience: 5
#  min_lr: 1e-6